[package]
name = "static-hedgedoc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
pulldown-cmark = "0.9.2"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0.162", features = ["derive"] }
